// Generated by gencpp from file messages/ChassisMode.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_CHASSISMODE_H
#define MESSAGES_MESSAGE_CHASSISMODE_H

#include <ros/service_traits.h>


#include <messages/ChassisModeRequest.h>
#include <messages/ChassisModeResponse.h>


namespace messages
{

struct ChassisMode
{

typedef ChassisModeRequest Request;
typedef ChassisModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChassisMode
} // namespace messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::messages::ChassisMode > {
  static const char* value()
  {
    return "40a1e51b6bb5a70a607d07454b9fd407";
  }

  static const char* value(const ::messages::ChassisMode&) { return value(); }
};

template<>
struct DataType< ::messages::ChassisMode > {
  static const char* value()
  {
    return "messages/ChassisMode";
  }

  static const char* value(const ::messages::ChassisMode&) { return value(); }
};


// service_traits::MD5Sum< ::messages::ChassisModeRequest> should match 
// service_traits::MD5Sum< ::messages::ChassisMode > 
template<>
struct MD5Sum< ::messages::ChassisModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::messages::ChassisMode >::value();
  }
  static const char* value(const ::messages::ChassisModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::ChassisModeRequest> should match 
// service_traits::DataType< ::messages::ChassisMode > 
template<>
struct DataType< ::messages::ChassisModeRequest>
{
  static const char* value()
  {
    return DataType< ::messages::ChassisMode >::value();
  }
  static const char* value(const ::messages::ChassisModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::messages::ChassisModeResponse> should match 
// service_traits::MD5Sum< ::messages::ChassisMode > 
template<>
struct MD5Sum< ::messages::ChassisModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::messages::ChassisMode >::value();
  }
  static const char* value(const ::messages::ChassisModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::ChassisModeResponse> should match 
// service_traits::DataType< ::messages::ChassisMode > 
template<>
struct DataType< ::messages::ChassisModeResponse>
{
  static const char* value()
  {
    return DataType< ::messages::ChassisMode >::value();
  }
  static const char* value(const ::messages::ChassisModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGES_MESSAGE_CHASSISMODE_H
