// Generated by gencpp from file messages/CheckStatusRequest.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_CHECKSTATUSREQUEST_H
#define MESSAGES_MESSAGE_CHECKSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct CheckStatusRequest_
{
  typedef CheckStatusRequest_<ContainerAllocator> Type;

  CheckStatusRequest_()
    : self_check_passed(false)  {
    }
  CheckStatusRequest_(const ContainerAllocator& _alloc)
    : self_check_passed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _self_check_passed_type;
  _self_check_passed_type self_check_passed;





  typedef boost::shared_ptr< ::messages::CheckStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::CheckStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckStatusRequest_

typedef ::messages::CheckStatusRequest_<std::allocator<void> > CheckStatusRequest;

typedef boost::shared_ptr< ::messages::CheckStatusRequest > CheckStatusRequestPtr;
typedef boost::shared_ptr< ::messages::CheckStatusRequest const> CheckStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::CheckStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::CheckStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'messages': ['/home/dji/roborts_ws/devel/share/messages/msg', '/home/dji/roborts_ws/src/RoboRTS/modules/stream/messages/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::CheckStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::CheckStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::CheckStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::CheckStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::CheckStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::CheckStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::CheckStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b302e58e815383eb0fa5c719a0e47f1a";
  }

  static const char* value(const ::messages::CheckStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb302e58e815383ebULL;
  static const uint64_t static_value2 = 0x0fa5c719a0e47f1aULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::CheckStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/CheckStatusRequest";
  }

  static const char* value(const ::messages::CheckStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::CheckStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool self_check_passed\n\
";
  }

  static const char* value(const ::messages::CheckStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::CheckStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.self_check_passed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::CheckStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::CheckStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "self_check_passed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.self_check_passed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_CHECKSTATUSREQUEST_H
