// Generated by gencpp from file messages/GameBuffStatus.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_GAMEBUFFSTATUS_H
#define MESSAGES_MESSAGE_GAMEBUFFSTATUS_H

#include <ros/service_traits.h>


#include <messages/GameBuffStatusRequest.h>
#include <messages/GameBuffStatusResponse.h>


namespace messages
{

struct GameBuffStatus
{

typedef GameBuffStatusRequest Request;
typedef GameBuffStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GameBuffStatus
} // namespace messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::messages::GameBuffStatus > {
  static const char* value()
  {
    return "2b948f4403813a06f105f67e07d5a55c";
  }

  static const char* value(const ::messages::GameBuffStatus&) { return value(); }
};

template<>
struct DataType< ::messages::GameBuffStatus > {
  static const char* value()
  {
    return "messages/GameBuffStatus";
  }

  static const char* value(const ::messages::GameBuffStatus&) { return value(); }
};


// service_traits::MD5Sum< ::messages::GameBuffStatusRequest> should match 
// service_traits::MD5Sum< ::messages::GameBuffStatus > 
template<>
struct MD5Sum< ::messages::GameBuffStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::messages::GameBuffStatus >::value();
  }
  static const char* value(const ::messages::GameBuffStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::GameBuffStatusRequest> should match 
// service_traits::DataType< ::messages::GameBuffStatus > 
template<>
struct DataType< ::messages::GameBuffStatusRequest>
{
  static const char* value()
  {
    return DataType< ::messages::GameBuffStatus >::value();
  }
  static const char* value(const ::messages::GameBuffStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::messages::GameBuffStatusResponse> should match 
// service_traits::MD5Sum< ::messages::GameBuffStatus > 
template<>
struct MD5Sum< ::messages::GameBuffStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::messages::GameBuffStatus >::value();
  }
  static const char* value(const ::messages::GameBuffStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::GameBuffStatusResponse> should match 
// service_traits::DataType< ::messages::GameBuffStatus > 
template<>
struct DataType< ::messages::GameBuffStatusResponse>
{
  static const char* value()
  {
    return DataType< ::messages::GameBuffStatus >::value();
  }
  static const char* value(const ::messages::GameBuffStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGES_MESSAGE_GAMEBUFFSTATUS_H
