// Generated by gencpp from file messages/GimbalModeRequest.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_GIMBALMODEREQUEST_H
#define MESSAGES_MESSAGE_GIMBALMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct GimbalModeRequest_
{
  typedef GimbalModeRequest_<ContainerAllocator> Type;

  GimbalModeRequest_()
    : gimbal_mode(0)  {
    }
  GimbalModeRequest_(const ContainerAllocator& _alloc)
    : gimbal_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _gimbal_mode_type;
  _gimbal_mode_type gimbal_mode;





  typedef boost::shared_ptr< ::messages::GimbalModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::GimbalModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalModeRequest_

typedef ::messages::GimbalModeRequest_<std::allocator<void> > GimbalModeRequest;

typedef boost::shared_ptr< ::messages::GimbalModeRequest > GimbalModeRequestPtr;
typedef boost::shared_ptr< ::messages::GimbalModeRequest const> GimbalModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::GimbalModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::GimbalModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'messages': ['/home/dji/roborts_ws/devel/share/messages/msg', '/home/dji/roborts_ws/src/RoboRTS/modules/stream/messages/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::GimbalModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::GimbalModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::GimbalModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::GimbalModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::GimbalModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::GimbalModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::GimbalModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c87f8568799ca64a2eed82fa85fa02bb";
  }

  static const char* value(const ::messages::GimbalModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc87f8568799ca64aULL;
  static const uint64_t static_value2 = 0x2eed82fa85fa02bbULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::GimbalModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/GimbalModeRequest";
  }

  static const char* value(const ::messages::GimbalModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::GimbalModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 gimbal_mode\n\
";
  }

  static const char* value(const ::messages::GimbalModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::GimbalModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gimbal_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::GimbalModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::GimbalModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "gimbal_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gimbal_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_GIMBALMODEREQUEST_H
