// Generated by gencpp from file messages/RfidInfo.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_RFIDINFO_H
#define MESSAGES_MESSAGE_RFIDINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace messages
{
template <class ContainerAllocator>
struct RfidInfo_
{
  typedef RfidInfo_<ContainerAllocator> Type;

  RfidInfo_()
    : header()
    , card_type(0)
    , card_idx(0)  {
    }
  RfidInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , card_type(0)
    , card_idx(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _card_type_type;
  _card_type_type card_type;

   typedef int16_t _card_idx_type;
  _card_idx_type card_idx;





  typedef boost::shared_ptr< ::messages::RfidInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::RfidInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RfidInfo_

typedef ::messages::RfidInfo_<std::allocator<void> > RfidInfo;

typedef boost::shared_ptr< ::messages::RfidInfo > RfidInfoPtr;
typedef boost::shared_ptr< ::messages::RfidInfo const> RfidInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::RfidInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::RfidInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'messages': ['/home/dji/roborts_ws/devel/share/messages/msg', '/home/dji/roborts_ws/src/RoboRTS/modules/stream/messages/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::RfidInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::RfidInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::RfidInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::RfidInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::RfidInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::RfidInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::RfidInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6068fcf6be5654b67a554d35cb390a35";
  }

  static const char* value(const ::messages::RfidInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6068fcf6be5654b6ULL;
  static const uint64_t static_value2 = 0x7a554d35cb390a35ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::RfidInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/RfidInfo";
  }

  static const char* value(const ::messages::RfidInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::RfidInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
#rfid card type: if type = 11, card is ICRA buff card\n\
int16 card_type\n\
\n\
#rfid card index\n\
int16 card_idx\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::messages::RfidInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::RfidInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.card_type);
      stream.next(m.card_idx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RfidInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::RfidInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::RfidInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "card_type: ";
    Printer<int16_t>::stream(s, indent + "  ", v.card_type);
    s << indent << "card_idx: ";
    Printer<int16_t>::stream(s, indent + "  ", v.card_idx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_RFIDINFO_H
