// Generated by gencpp from file messages/SelfCheckResponse.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_SELFCHECKRESPONSE_H
#define MESSAGES_MESSAGE_SELFCHECKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct SelfCheckResponse_
{
  typedef SelfCheckResponse_<ContainerAllocator> Type;

  SelfCheckResponse_()
    : passed(false)  {
    }
  SelfCheckResponse_(const ContainerAllocator& _alloc)
    : passed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _passed_type;
  _passed_type passed;





  typedef boost::shared_ptr< ::messages::SelfCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::SelfCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SelfCheckResponse_

typedef ::messages::SelfCheckResponse_<std::allocator<void> > SelfCheckResponse;

typedef boost::shared_ptr< ::messages::SelfCheckResponse > SelfCheckResponsePtr;
typedef boost::shared_ptr< ::messages::SelfCheckResponse const> SelfCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::SelfCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::SelfCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'messages': ['/home/dji/roborts_ws/devel/share/messages/msg', '/home/dji/roborts_ws/src/RoboRTS/modules/stream/messages/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::SelfCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::SelfCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::SelfCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::SelfCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::SelfCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::SelfCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::SelfCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18e896fced617e691ee2fff3736d1110";
  }

  static const char* value(const ::messages::SelfCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18e896fced617e69ULL;
  static const uint64_t static_value2 = 0x1ee2fff3736d1110ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::SelfCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/SelfCheckResponse";
  }

  static const char* value(const ::messages::SelfCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::SelfCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool passed\n\
";
  }

  static const char* value(const ::messages::SelfCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::SelfCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.passed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelfCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::SelfCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::SelfCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "passed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.passed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_SELFCHECKRESPONSE_H
