// Generated by gencpp from file messages/ShootModeControl.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_SHOOTMODECONTROL_H
#define MESSAGES_MESSAGE_SHOOTMODECONTROL_H

#include <ros/service_traits.h>


#include <messages/ShootModeControlRequest.h>
#include <messages/ShootModeControlResponse.h>


namespace messages
{

struct ShootModeControl
{

typedef ShootModeControlRequest Request;
typedef ShootModeControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShootModeControl
} // namespace messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::messages::ShootModeControl > {
  static const char* value()
  {
    return "03450b1a1a21c651312ad46d1cfacf66";
  }

  static const char* value(const ::messages::ShootModeControl&) { return value(); }
};

template<>
struct DataType< ::messages::ShootModeControl > {
  static const char* value()
  {
    return "messages/ShootModeControl";
  }

  static const char* value(const ::messages::ShootModeControl&) { return value(); }
};


// service_traits::MD5Sum< ::messages::ShootModeControlRequest> should match 
// service_traits::MD5Sum< ::messages::ShootModeControl > 
template<>
struct MD5Sum< ::messages::ShootModeControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::messages::ShootModeControl >::value();
  }
  static const char* value(const ::messages::ShootModeControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::ShootModeControlRequest> should match 
// service_traits::DataType< ::messages::ShootModeControl > 
template<>
struct DataType< ::messages::ShootModeControlRequest>
{
  static const char* value()
  {
    return DataType< ::messages::ShootModeControl >::value();
  }
  static const char* value(const ::messages::ShootModeControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::messages::ShootModeControlResponse> should match 
// service_traits::MD5Sum< ::messages::ShootModeControl > 
template<>
struct MD5Sum< ::messages::ShootModeControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::messages::ShootModeControl >::value();
  }
  static const char* value(const ::messages::ShootModeControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::ShootModeControlResponse> should match 
// service_traits::DataType< ::messages::ShootModeControl > 
template<>
struct DataType< ::messages::ShootModeControlResponse>
{
  static const char* value()
  {
    return DataType< ::messages::ShootModeControl >::value();
  }
  static const char* value(const ::messages::ShootModeControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGES_MESSAGE_SHOOTMODECONTROL_H
