// Generated by gencpp from file cvCamera/cameraTip.msg
// DO NOT EDIT!


#ifndef CVCAMERA_MESSAGE_CAMERATIP_H
#define CVCAMERA_MESSAGE_CAMERATIP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cvCamera
{
template <class ContainerAllocator>
struct cameraTip_
{
  typedef cameraTip_<ContainerAllocator> Type;

  cameraTip_()
    : camera_info(0)
    , camera_check(false)  {
    }
  cameraTip_(const ContainerAllocator& _alloc)
    : camera_info(0)
    , camera_check(false)  {
  (void)_alloc;
    }



   typedef int16_t _camera_info_type;
  _camera_info_type camera_info;

   typedef uint8_t _camera_check_type;
  _camera_check_type camera_check;





  typedef boost::shared_ptr< ::cvCamera::cameraTip_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cvCamera::cameraTip_<ContainerAllocator> const> ConstPtr;

}; // struct cameraTip_

typedef ::cvCamera::cameraTip_<std::allocator<void> > cameraTip;

typedef boost::shared_ptr< ::cvCamera::cameraTip > cameraTipPtr;
typedef boost::shared_ptr< ::cvCamera::cameraTip const> cameraTipConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cvCamera::cameraTip_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cvCamera::cameraTip_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cvCamera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cvCamera': ['/home/dji/catkin_ws_42/src/cvCamera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cvCamera::cameraTip_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cvCamera::cameraTip_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cvCamera::cameraTip_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cvCamera::cameraTip_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cvCamera::cameraTip_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cvCamera::cameraTip_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cvCamera::cameraTip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79b4799b7c29d94aabd168ac1a8c0042";
  }

  static const char* value(const ::cvCamera::cameraTip_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79b4799b7c29d94aULL;
  static const uint64_t static_value2 = 0xabd168ac1a8c0042ULL;
};

template<class ContainerAllocator>
struct DataType< ::cvCamera::cameraTip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cvCamera/cameraTip";
  }

  static const char* value(const ::cvCamera::cameraTip_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cvCamera::cameraTip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
# 0: left 1: right\n\
int16 camera_info\n\
bool camera_check\n\
";
  }

  static const char* value(const ::cvCamera::cameraTip_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cvCamera::cameraTip_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_info);
      stream.next(m.camera_check);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cameraTip_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cvCamera::cameraTip_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cvCamera::cameraTip_<ContainerAllocator>& v)
  {
    s << indent << "camera_info: ";
    Printer<int16_t>::stream(s, indent + "  ", v.camera_info);
    s << indent << "camera_check: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.camera_check);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CVCAMERA_MESSAGE_CAMERATIP_H
