; Auto-generated. Do not edit!


(cl:in-package messages-msg)


;//! \htmlinclude caissonDetectionResult.msg.html

(cl:defclass <caissonDetectionResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:float
    :initform 0.0))
)

(cl:defclass caissonDetectionResult (<caissonDetectionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <caissonDetectionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'caissonDetectionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name messages-msg:<caissonDetectionResult> is deprecated: use messages-msg:caissonDetectionResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <caissonDetectionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader messages-msg:result-val is deprecated.  Use messages-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <caissonDetectionResult>) ostream)
  "Serializes a message object of type '<caissonDetectionResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <caissonDetectionResult>) istream)
  "Deserializes a message object of type '<caissonDetectionResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'result) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<caissonDetectionResult>)))
  "Returns string type for a message object of type '<caissonDetectionResult>"
  "messages/caissonDetectionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'caissonDetectionResult)))
  "Returns string type for a message object of type 'caissonDetectionResult"
  "messages/caissonDetectionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<caissonDetectionResult>)))
  "Returns md5sum for a message object of type '<caissonDetectionResult>"
  "db954e5de3aba73b237d07575e5cac28")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'caissonDetectionResult)))
  "Returns md5sum for a message object of type 'caissonDetectionResult"
  "db954e5de3aba73b237d07575e5cac28")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<caissonDetectionResult>)))
  "Returns full string definition for message of type '<caissonDetectionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'caissonDetectionResult)))
  "Returns full string definition for message of type 'caissonDetectionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <caissonDetectionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <caissonDetectionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'caissonDetectionResult
    (cl:cons ':result (result msg))
))
